sudo: false
language: python
python:
- '3.5'
services:
- docker
before_install: docker build -t antlr_plsql .
script: docker run -v $(pwd):/usr/src/app antlr_plsql make build test
deploy:
  provider: pypi
  user: datacamp
  password:
    secure: sFMACOnPcBSb5dFCQX3tVz/f8C6ZJVzjEFLyTaD6YbIyIEu2VWDzLyXG9HEgZAjVKagbaGfcN6PmNAIVKa9UZBZ1xWRhWQ1YBNmM1/V+dlw3XzpPlD0tMboU1kX+GVhiYov6k3G3Ts/2zdGsiSjFN3xqQVJwLXVET4M6QM81e1X8p7laJ868HbW702QEUg8p1XtKUiQOhQFTdbqnbiMM/BAMmrxX2sLghthp4d4VHxuo3C/klycUc/cfmAMEYxutku9F2rfmPH2k95HJFnSjYv9UqJpxMbxcdyUd14ibh3V1Ofn/KkKYghiIf7f8q+wjpoZxbty2VYj/XFbkDpqpebf4hazb5mTobSYNAV5hHwgYpwdsFUvhsSQU2Sae6+txkpaZhhn5q/TRRw/r/Gno4hmgUC9AInFTNGw9entQT0iiUs5yMQj4Yz+Kfiyux/Y+/YWxfMkVc+9j6ODHf0Mb0843mbklQ+ABY3NSOt1SMVAJ/ohWtURHZpyw7GArPPiXCC7d5DIAMgqVxhv4W/u3yRFTAtrxoPd7ngwRmIDyQcsobALJlxx/JFT2I9ZGs4zjdzP76qjR3G0aQ2WmDThyvgqzx/pAy5s+ITOOSv1OeaeiAjOjPp94h0trbk0H9/ir/Mi0Ll0DF1mAPR8HJAPn/6UqMQjWwShdbnB3xNROamU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: datacamp/antlr-plsql
  skip_cleanup: true
  skip_upload_docs: true
